package com.core.jpatraining2.repository;

import com.core.jpatraining2.entity.Users;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;

import java.util.List;

public interface UserRepository extends JpaRepository<Users, Long> {

    // everything will auto generated by JpaRepository like save, findById, findAll, delete.
    // but you can also give some query if it needed
    // sample here we findUniqueUsername
    @Query("SELECT u FROM Users u WHERE u.username = :username")
    List<Users> findUniqueUsername(@Param("username") String username);
}
